services:
  nestjs_api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./test/Dockerfile
    image: testing-docker-nestjs
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=Testing
    volumes:
      - ./src:/usr/src/app/src
