services:
  nestjs_api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - NODE_ENV=Production
    volumes:
      - ./src:/usr/src/app/src
